"""Test pylint settings."""
import filecmp
from pathlib import Path

from .cnn.visualization import USE_KERAS_VIS
from .run_all import collect_arguments, download_data
from .run_cnn import run_cnn


def test_reproducibility(tmp_path: Path) -> None:
    """Test that run_all yields reproducible results."""
    download_data()
    run_dirs = {}
    for run in ("0same", "2diff", "1same"):
        run_id = f"ReproTest-{run}"
        results_dir = tmp_path
        seed = 0 if run.endswith("same") else 1
        args = collect_arguments(
            # fmt: off
            # define data
            "--run-id", run_id,
            "--dataset", "INF_R_153_CE",
            "--pretraining", "imagenet",
            # define test
            "--results-dir", results_dir,
            "--seed", seed,
            "--fast-try",
        )
        run_dirs[run] = run_cnn(*args)

    files = {
        file.relative_to(run_dir)
        for run_dir in run_dirs.values()
        for file in run_dir.glob("**/*")
        if file.is_file()
        # .pb files include autogenerated function suffixes which differ when saving a
        # model multiple times from the same process. Fortunately, we are happy enough
        # if the weights files are equal. Alternatively, we might replace
        # run_cnn(*args) above with subprocess.run(["itrade-run-cnn", *map(str, args)]).
        # fingerprint.pb files (saving model hashes since TensorFlow 2.12) also differ,
        # and in TensorFlow 2.13.0rc0, "keras_metadata.pb" show differences ("input_2"
        # vs. "input_1").
        and file.suffix != ".pb"
    }
    assert len(files) > 0

    (equal, different, error) = filecmp.cmpfiles(
        run_dirs["0same"], run_dirs["2diff"], files, shallow=False
    )
    assert len(equal) < len(files)
    assert len(different) > 0
    assert len(error) == 0

    (equal, different, error) = filecmp.cmpfiles(
        run_dirs["0same"], run_dirs["1same"], files, shallow=False
    )
    assert len(equal) == len(files)
    assert len(different) == 0
    assert len(error) == 0


def test_visualization(tmp_path: Path) -> None:
    """Test that model visualization works."""
    assert USE_KERAS_VIS

    download_data()
    args = collect_arguments(
        # fmt: off
        "--run-id", "VisTest",
        "--dataset", "INF_R_1025_primary_V2_DS1",
        "--no-train",
        "--vis-model",
        "--results-dir", tmp_path,
        "--fast-try",
    )
    run_dir = run_cnn(*args)

    vis_dir = run_dir / "visualization"
    assert vis_dir.is_dir()
    assert next(vis_dir.iterdir(), None) is not None
